#!/bin/bash

# Cloudflare Pages Deployment Script
# TED Protocol Whitepaper

echo "🚀 Cloudflare Pages 배포 준비 완료!"
echo "===================================="
echo ""
echo "📋 수동 배포 방법:"
echo ""
echo "1️⃣ Cloudflare Dashboard 접속:"
echo "   https://dash.cloudflare.com/"
echo ""
echo "2️⃣ Pages 섹션 선택 (왼쪽 메뉴)"
echo ""
echo "3️⃣ 'Create a project' 클릭"
echo ""
echo "4️⃣ 'Upload assets' 선택"
echo ""
echo "5️⃣ 프로젝트 설정:"
echo "   - Project name: ted-protocol-whitepaper"
echo "   - Upload folder: $(pwd)/build"
echo ""
echo "6️⃣ 'Deploy site' 클릭"
echo ""
echo "📁 빌드 폴더 위치:"
echo "   $(pwd)/build"
echo ""
echo "✅ 빌드 완료 상태:"
ls -la build/ | head -5
echo ""
echo "🌐 배포 후 URL:"
echo "   https://ted-protocol-whitepaper.pages.dev"
echo ""
echo "📝 참고: API 토큰 생성됨"
echo "   Token ID: cc923f47e37a03d61b910dcd46ecf9aa"
echo "   Token Value: XyHBgwFg9VWtIZuEFzT9yJodaQTq72xolrUXM4YW"
echo ""
echo "💡 팁: 자동 배포를 원하시면 GitHub 리포지토리를 Cloudflare Pages와 연결하세요."